### ISSUE TITLE
perlPackages.CryptEd25519 missing

### ISSUE THREAD

**Issue by Mic92** [thoughtpolice/eris#1]
Looks it is not yet available in nixpkgs

**Comment by thoughtpolice** [comment]
This is actually an oversight; when I was testing `CryptEd25519` for 'automatic keying' earlier in development it seemed as if may not actually use the same signature format that `libsodium`'s `crypt_sign` uses, so I removed it since it couldn't quite work (there's a bit of history here IIRC, but the original version of Ed25519 used a slightly different signature format than the later, more popular versions you see everywhere else). Alternatively, I screwed something up.

Either way, this dependency can be deleted for now and I can re-evaluate its inclusion (or replacement) later.

**Comment by thoughtpolice** [comment]
(And also, to be clear, this will only happen when using the module, based on your `NIX_PATH` of course; the module uses the NixOS's passed `pkgs` variable for the set of dependencies when compiling, while `release.nix` uses a hard-coded commit. I'm not sure if this is the _right_ or most obvious thing to do, but bloating the closure of any NixOS user to keep an entirely separate copy of Perl, etc around seems a bit unfortunate.)

**Comment by Mic92** [comment]
It is still used in eris.pl though.

**Comment by thoughtpolice** [comment]
Oh, so it is! I'll look into getting rid of it for now, I think.

**Comment by thoughtpolice** [comment]
Oh, and to be super clear (for any other readers), the `perlPackages.CryptEd25519` expression is simply not available in `nixpkgs-18.09`, but is in `master`, so I'm guessing this might have been where this came from, too.

**Comment by Mic92** [comment]
Oh, I must have had checked out 18.09 when testing this? It was even included in my nixpkgs fork that follows master more or less. Well, now it works for everyone.
